%%{init: {'theme': 'dark', 'themeVariables': { 'darkMode': true, 'background': '#0e121a'}}}%%
flowchart TD
    subgraph STACK ["Stack"]
        direction TB

        subgraph C2 ["activo: bool = true"]
            DIR2["0x7FFEE4B2A894"]:::dirStyle
            T2["1 Byte (8 bits)"]
            VAL2["00000001 (0x01)"]:::valStyle
        end

        subgraph C1 ["edad: i32 = 25"]
            DIR1["0x7FFEE4B2A890"]:::dirStyle
            T1["4 Bytes (32 bits)"]
            VAL1["00000000 00000000 00000000 00011001 (0x19)"]:::valStyle
        end
    end

    SP["Stack Pointer (SP)"]:::spStyle
    SP --> C2

    classDef default fill:#161c28,stroke:#456090,stroke-width:1.5px,color:#ffffff;
    classDef dirStyle fill:#080c12,stroke:#64c8ff,stroke-width:1.5px,color:#64c8ff;
    classDef valStyle fill:#141c2b,stroke:#38bdf8,stroke-width:1px,color:#f8fafc;
    classDef spStyle fill:#2d1b0d,stroke:#ffa032,stroke-width:2px,color:#ffa032;
