%%{init: {'theme': 'dark', 'themeVariables': { 'darkMode': true, 'background': '#0e121a'}}}%%
flowchart TD
    subgraph STACK ["STACK (LIFO)"]
        direction TB

        subgraph C2 ["activo: bool = true"]
            DIR2["MEMORY ADDRESS: 0x7FFEE4B2A894"]:::dirStyle
            T2["SIZE: 1 Byte (8 bits)"]:::sizeStyle
            VAL2["VALUE:<br/>Binario: 00000001<br/>Hex: 0x01"]:::valStyle
        end

        subgraph C1 ["edad: i32 = 25"]
            DIR1["MEMORY ADDRESS: 0x7FFEE4B2A890"]:::dirStyle
            T1["SIZE: 4 Bytes (32 bits)"]:::sizeStyle
            VAL1["VALUE:<br/>00000000 00000000<br/>00000000 00011001<br/>Hex: 0x00000019"]:::valStyle
        end
    end

    SP["Stack Pointer (SP)"]:::spStyle
    SP --> C2

    classDef default fill:#141c2b,stroke:#2d3c5a,stroke-width:1.2px,color:#ffffff;
    classDef dirStyle fill:#080c12,stroke:#64c8ff,stroke-width:1.2px,color:#64c8ff;
    classDef sizeStyle fill:#080c12,stroke:#456090,stroke-width:1.2px,color:#ffffff;
    classDef valStyle fill:#080c12,stroke:#38bdf8,stroke-width:1.2px,color:#64c8ff;
    classDef spStyle fill:#26180a,stroke:#ffa032,stroke-width:1.8px,color:#ffa032;
