%%{init: {'theme': 'dark', 'themeVariables': { 'darkMode': true, 'background': '#0f172a'}}}%%
flowchart TD
    %% ===================================================
    %% RUN TIME (RESUMIDO Y TÉCNICO)
    %% ===================================================

    BIN["<b>Ejecutable Binario</b>"]

    R1["<b>Kernel SO</b><br/>Mapeo a Memoria Virtual"]
    R2["<b>Segmentación de Memoria</b><br/>Stack + Heap"]
    R3["<b>Ejecución Directa en CPU</b><br/>Instrucciones Nativas x86_64/ARM<br/><i>(Sin VM / Sin Intérprete / Sin GC)</i>"]
    R4["<b>RAII</b><br/>Llamada determinista a drop() al salir del Scope"]

    EXIT(["<b>Cero Fugas</b>"]):::targetNode

    BIN --> R1 --> R2 --> R3 --> R4 --> EXIT

    classDef targetNode fill:#059669,stroke:#34d399,stroke-width:2.5px,color:#ffffff;
    classDef default fill:#1e293b,stroke:#38bdf8,stroke-width:1.5px,color:#f8fafc;

    style BIN fill:#1e1e38,stroke:#818cf8,stroke-width:2px,color:#c7d2fe
    style R1 fill:#1e293b,stroke:#38bdf8,stroke-width:1.5px,color:#f8fafc
    style R2 fill:#1e293b,stroke:#818cf8,stroke-width:1.5px,color:#f8fafc
    style R3 fill:#1e293b,stroke:#10b981,stroke-width:2px,color:#a7f3d0
    style R4 fill:#2d1508,stroke:#f97316,stroke-width:1.5px,color:#fed7aa
